server:
  port: 8087

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: admin
          uri: lb://ADMIN
          predicates:
            - Path=/admin/**
        - id: history
          uri: lb://HISTORY
          predicates:
            - Path=/history/**

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/